# Generated by Django 3.2.4 on 2021-08-27 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=200)),
                ('dateOfJoining', models.DateField(blank=True, default=datetime.datetime.now)),
                ('departmentName', models.CharField(max_length=200)),
                ('photoFileUrl', models.FileField(upload_to='image')),
            ],
        ),
    ]
